module.exports = {
    AuthControllers: require('./auth_controllers'),
    UserControllers: require('./user_controllers'),
    SchoolControllers: require('./school_controllers'),
    CategoryControllers: require('./category_controllers'),
    SubCategoryControllers: require('./sub_categories_controllers'),
    UserAddressControllers: require('./user_address_controllers'),
    ProductControllers: require('./products_controllers'),
    CartsControllers: require('./cart_controllers'),
    WishlistControllers: require('./wishlist_controllers'),
    OrdersControllers: require('./orders_controllers'),
    DeliverTypesControllers: require('./deliver_types_controllers'),
    BannerControllers: require('./banners_controllers'),
    SimilarProductControllers: require('./similar_product_controllers'),
    AttributesControllers: require('./attributes_controllers'),
}